<a href="https://colab.research.google.com/github/suhaib-us/MachineLearning/blob/main/FundmentalsOfPytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### FUNDAMENTALS OF PYTORCH

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


 Introduction to Tensors

 creating tensor

In [ ]:
#scalar
scalar=torch.tensor(33)
scalar

tensor(33)

PyTorch Tensors are created using "torch.tensor()".


In [ ]:
scalar.ndim


0

In [ ]:
#get tensor back as python int
scalar.item()

33

In [ ]:
#vector
vector=torch.tensor([5,5])
vector

tensor([5, 5])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#Matrix
matrix = torch.tensor([[3,5],[4,6]])
matrix

tensor([[3, 5],
        [4, 6]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
matrix[0]

tensor([3, 5])

###Random Tensor

In [ ]:
##create random tensor of size (3,4)
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.8133, 0.5120, 0.4949, 0.1180],
         [0.2740, 0.3565, 0.6786, 0.0600],
         [0.7619, 0.0987, 0.8431, 0.5288]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
random_tensor.size()

torch.Size([1, 3, 4])

In [ ]:
##create a random tensor similar shape to image tensor
random_image_size_tensor = torch.rand(size=(2,54,65)) ## colour channel, height,width
random_image_size_tensor


tensor([[[0.2878, 0.2216, 0.7931,  ..., 0.2003, 0.3775, 0.4856],
         [0.3047, 0.4224, 0.1234,  ..., 0.5645, 0.7214, 0.8443],
         [0.3506, 0.7880, 0.0165,  ..., 0.8269, 0.4751, 0.2399],
         ...,
         [0.9246, 0.2509, 0.3400,  ..., 0.2229, 0.2063, 0.4571],
         [0.7663, 0.8708, 0.4507,  ..., 0.0185, 0.4711, 0.4822],
         [0.5585, 0.0540, 0.2126,  ..., 0.2872, 0.0453, 0.1105]],

        [[0.8942, 0.5313, 0.5491,  ..., 0.0494, 0.9467, 0.3610],
         [0.9080, 0.2093, 0.6821,  ..., 0.1424, 0.1980, 0.2921],
         [0.2973, 0.7272, 0.6037,  ..., 0.0845, 0.6593, 0.9361],
         ...,
         [0.9902, 0.0182, 0.7686,  ..., 0.2326, 0.5083, 0.4217],
         [0.1638, 0.3567, 0.9268,  ..., 0.0909, 0.8216, 0.0340],
         [0.6978, 0.8548, 0.6167,  ..., 0.8059, 0.1440, 0.5112]]])

###Zeros and Ones

In [ ]:
## zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros.dtype

torch.float32

In [ ]:
zeros*random_tensor  ##dimension should be same .

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
#ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

###### creating a range of tensors and tensor like.


In [ ]:
##using torch.range()
x = torch.arange(start=0,end=190,step=2)
x



tensor([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
         28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,  54,
         56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,
         84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104, 106, 108, 110,
        112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138,
        140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166,
        168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188])

In [ ]:
## creating tensor like
ten_zeros=torch.zeros_like(input = x) # input is tensor
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor datatypes
Note: 3 errors in deep learning and pytorch using tensor datatypes
1.  Tensors not right shape
2.  Tensors not the right datatype
3.  Tensors not on the right device

In [ ]:
##float32 by default
float_32_tensor = torch.tensor([2.0,4.5,5.2],
                               dtype= None,# what datatype is presnt
                               device='cpu',#depends on what we need
                               requires_grad=False# prevents copying
                               )

float_32_tensor

tensor([2.0000, 4.5000, 5.2000])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
##coversion of flaot 32 to flaot 16
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([2.0000, 4.5000, 5.1992], dtype=torch.float16)

In [ ]:
float_32_tensor * float_16_tensor

tensor([ 4.0000, 20.2500, 27.0359])

In [ ]:
## 32-bit integer (signed)
int_32_tensor =torch.tensor([3,5,2],dtype=torch.int32)
int_32_tensor

tensor([3, 5, 2], dtype=torch.int32)

In [ ]:
int_32_tensor * float_32_tensor

tensor([ 6.0000, 22.5000, 10.4000])

In [ ]:
float_16_tensor *int_32_tensor

tensor([ 6.0000, 22.5000, 10.3984], dtype=torch.float16)

###Tensor manipulation (tensor operations)
1. add
2. sub
3. multiply element wise
4. divsion
5. matrix multiply

In [ ]:
#creating a tensor and add 27 to it
tensor = torch.tensor([2,5,3])
tensor + 27
# tensor multiply
tensor * 17
# tensor subtract
tensor - 32

tensor([-30, -27, -29])

In [ ]:
# inbuilt function for torch multiplicatoin
torch.mul(tensor,234)

tensor([ 468, 1170,  702])

###Matrix multiplication
1. element wise
2. matrix multiplication(dot product)

rules for tensor multiplication
 1.  Inner dimensions must match
   * (3,2) @ (3,2) wil not work.
  * (2,3) @ (3,2) will work.
   * (3,2) @ (2,3) will work.

  2. the resultant matrix has the shape  of outer dimensions.
   * (3,2) @ (2,3) has shape (3,3)

In [ ]:
 tensor = torch.matmul(torch.rand(3,2), torch.rand(3,2)) # RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
 ##element wise multiply
print(tensor,"*",tensor)
print(f"equals: {tensor*tensor}")

tensor([2, 5, 3]) * tensor([2, 5, 3])
equals: tensor([ 4, 25,  9])


In [ ]:
tensor

tensor([2, 5, 3])

In [ ]:
#matrix multiply
torch.matmul(tensor,tensor)

tensor(38)

In [ ]:
## matrix multiplication by hand
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
  print(value)

tensor(4)
tensor(29)
tensor(38)
CPU times: user 4.62 ms, sys: 9 µs, total: 4.63 ms
Wall time: 4.82 ms


In [ ]:
%%time
torch.matmul(tensor,tensor) # this function is very fast than multiplying by hand


CPU times: user 1.47 ms, sys: 0 ns, total: 1.47 ms
Wall time: 7.63 ms


tensor(38)

In [ ]:
tensor = torch.rand(2,20,4)
tensor

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
  print(value)

tensor(4)
tensor(29)
tensor(38)
CPU times: user 2.76 ms, sys: 0 ns, total: 2.76 ms
Wall time: 2.76 ms




### One of the most common errors in deep learning is : SHAPE Error



In [ ]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)



We can make matrix multiplication work between tensor_A and tensor_B by making their inner dimensions match.

One of the ways to do this is with a transpose (switch the dimensions of a given tensor)

In [ ]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [ ]:
# View tensor_A and tensor_B.T
print(tensor_A.T)
print(tensor_B)

tensor([[1., 3., 5.],
        [2., 4., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [ ]:
torch.matmul(tensor_A.T, tensor_B)

tensor([[ 76., 103.],
        [100., 136.]])

In [ ]:
# The operation works when tensor_B is transposed
print(f"orginal shape: tensor_A = {tensor_A.shape}, tensor_B ={tensor_B.shape}\n")
print(f"new shape: tensor_A.T = {tensor_A.T.shape}, tensor_B ={tensor_B.shape}\n")
print(f"multiplying: {torch.matmul(tensor_A.T,tensor_B)}\n")
print("Output:\n")
output = torch.matmul(tensor_A.T, tensor_B)
print(output)
print(f"\nOutput shape: {output.shape}")

orginal shape: tensor_A = torch.Size([3, 2]), tensor_B =torch.Size([3, 2])

new shape: tensor_A.T = torch.Size([2, 3]), tensor_B =torch.Size([3, 2])

multiplying: tensor([[ 76., 103.],
        [100., 136.]])

Output:

tensor([[ 76., 103.],
        [100., 136.]])

Output shape: torch.Size([2, 2])


### Tensor aggregation( finding mean,sum,min,max)

In [ ]:
#creating a tensor
x = torch.arange(2,7,1)
x

tensor([2, 3, 4, 5, 6])

In [ ]:
#finding min
x.min(),torch.min(x)

(tensor(2), tensor(2))

In [ ]:
#finding max
torch.max(x), x.max()



(tensor(6), tensor(6))

In [ ]:
#finding sum
torch.sum(x), x.sum()

(tensor(20), tensor(20))

In [ ]:
#mean wont work without float dtype
torch.mean(x), x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

###wrong datatype error in DL

In [ ]:
## Finding mean
torch.mean(x.type(torch.float16)),x.type(torch.float32).mean() ## won't work without float datatype


(tensor(4., dtype=torch.float16), tensor(4.))

### Find the positional min and max

In [ ]:
# finding min and max
x.argmin(),x.argmax()

(tensor(0), tensor(4))

In [ ]:
x[0]

tensor(2)

###Reshaping, stacking, squeezing and unsqueezing

Why do any of these?

Because deep learning models (neural networks) are all about manipulating tensors in some way. And because of the rules of matrix multiplication, if you've got shape mismatches, you'll run into errors. These methods help you make sure the right elements of your tensors are mixing with the right elements of other tensors.

Here is a summary of the methods with their one-line descriptions corrected for clarity:

1. **torch.reshape(input, shape)**
   - Reshapes input to the specified shape (if compatible).

2. **Tensor.view(shape)**
   - Returns a view of the original tensor in a different shape but shares the same data as the original tensor.

3. **torch.stack(tensors, dim=0)**
   - Concatenates a sequence of tensors along a new dimension (dim); all tensors must be the same size.

4. **torch.squeeze(input)**
   - Squeezes input to remove all dimensions with size 1.

5. **torch.unsqueeze(input, dim)**
   - Returns input with a dimension of size 1 added at the specified dim.

6. **torch.permute(input, dims)**
   - Returns a view of the original input with its dimensions permuted (rearranged) to the specified dims.

In [ ]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

### Squeezing

In [ ]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [ ]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


### Permute

In [ ]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing (selecting data from tensors)
   indexing in pytorch is similar to indexing in numpy

In [ ]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [ ]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

###PyTorch tensors & NumPy

In [ ]:
import torch
import numpy as np
# numpy to tensor
array = np.arange(1.08)
tensor = torch.from_numpy(array)  # will be dtype=float32 unless changed
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
##tensor to. numpy array
tensor = torch.ones(5)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1.]), array([1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
#changing the tensor ? what will happen to numpy_tensor
tensor = tensor+1
tensor,numpy_tensor   # numpy_tensor remains unchanged i,e they dont share memory

(tensor([4., 4., 4., 4., 4.]), array([1., 1., 1., 1., 1.], dtype=float32))

###
Reproducibility (trying to take the random out of random


In [ ]:
import torch
# set the random seed
RANDOM_SEED = 23
torch.manual_seed(RANDOM_SEED)
x = torch.rand(2,3)

torch.manual_seed(RANDOM_SEED)
y = torch.rand(2,3)

print(x)
print(y)
print(x == y)


tensor([[0.4283, 0.2889, 0.4224],
        [0.3571, 0.9577, 0.1100]])
tensor([[0.4283, 0.2889, 0.4224],
        [0.3571, 0.9577, 0.1100]])
tensor([[True, True, True],
        [True, True, True]])
